apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: httptest
spec:
  selector:
      matchLabels:
        run: nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx-1
        image: pchahal24/http_test:latest
        imagePullPolicy: Always
        ports:
          - name: port-80
            containerPort: 80
            protocol: TCP
          - name: port-443
            containerPort: 443
            protocol: TCP
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 256Mi
