apiVersion: v1
kind: Service
metadata:
  name: httptest-service
  namespace: httptest
  labels:
    app: httptest
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 80
    protocol: TCP
    name: port-80
    targetPort: 80
  - port: 443
    protocol: TCP
    name: port-443
    targetPort: 443
  selector:
    run: httptest
  type: LoadBalancer